# /etc/nix/nix.conf
experimental-features = nix-command flakes
# auto-optimise-store = true
trusted-users = root smagh
substituters = https://cache.nixos.org/
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
keep-outputs = false
keep-derivations = false
min-free = 1073741824 # 1GB
max-free = 5368709120 # 5GB
access-tokens = github.com=<replace-with-token>
