# llama-server --models-preset ~/.config/llama/config.ini --models-max 2 --host 0.0.0.0 --port 8081
version = 1

[*]
host = 0.0.0.0
port = 8080
# Prompting
jinja = true
; cache-type-k = q8_0
; cache-type-v = q8_0

# -----------------------------
# MODELS
# -----------------------------
[gemma-4-26B-A4B-it-UD-Q4_K_XL]
alias = 26B-A4B
hf = unsloth/gemma-4-26B-A4B-it-GGUF:UD-Q4_K_XL
ctx-size = 65536
image-min-tokens = 560
image-max-tokens = 1120
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.05
reasoning = off
flash-attn = on

[gemma-4-E4B-it-Q4_K_S]
alias = E4B
hf = unsloth/gemma-4-E4B-it-GGUF:Q4_K_S
ctx-size = 32768
image-min-tokens = 560
image-max-tokens = 1120
temp = 1.0
top-p = 0.95
top-k = 64
min-p = 0.05
reasoning = off

[Qwen3.5-9B-UD-Q4_K_XL]
alias = Qwen3.5-9B
hf = unsloth/Qwen3.5-9B-GGUF:UD-Q4_K_XL
ctx-size = 131072
reasoning = on
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0

[Qwen3.6-35B-A3B-Q4_K_S]
alias = Qwen3.6-35B
hf = unsloth/Qwen3.6-35B-A3B-GGUF:Q4_K_S
ctx-size = 65536
reasoning = on
flash-attn = on
temp = 0.8
top-p = 0.95
top-k = 40
min-p = 0.05
presence-penalty = 0.0
repeat-penalty = 1.0
chat-template-kwargs = {"preserve_thinking": true}

[Qwen3.6-27B-Q4_K_M]
alias = Qwen3.6-27B
hf = unsloth/Qwen3.6-27B-GGUF:Q4_K_M
ctx-size = 65536
flash-attn = on
reasoning = on
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0
chat-template-kwargs = {"preserve_thinking": true}
